/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab5;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author dessi
 */
public class MainNintendo extends javax.swing.JFrame {

    /**
     * Creates new form MainNintendo
     */
    public MainNintendo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_LogIn = new javax.swing.JLabel();
        jLabel2_Login1 = new javax.swing.JLabel();
        jTextField1_Usuario = new javax.swing.JTextField();
        jLabel3_Login = new javax.swing.JLabel();
        jTextField2_Contraseña = new javax.swing.JTextField();
        jButton1_Login = new javax.swing.JButton();
        jButton2_Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1_LogIn.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1_LogIn.setText("Log In");

        jLabel2_Login1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2_Login1.setText("Usuario:");

        jTextField1_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_UsuarioActionPerformed(evt);
            }
        });

        jLabel3_Login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3_Login.setText("Contraseña:");

        jTextField2_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_ContraseñaActionPerformed(evt);
            }
        });

        jButton1_Login.setText("Ingresar");
        jButton1_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LoginActionPerformed(evt);
            }
        });

        jButton2_Login.setText("Registrarme");
        jButton2_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1_LogIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3_Login)
                            .addComponent(jTextField1_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_Login1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2_Login))
                                .addComponent(jTextField2_Contraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1_LogIn)
                .addGap(23, 23, 23)
                .addComponent(jLabel2_Login1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3_Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Login)
                    .addComponent(jButton2_Login))
                .addGap(43, 43, 43))
        );

        getAccessibleContext().setAccessibleName("LogIn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_UsuarioActionPerformed

    private void jTextField2_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_ContraseñaActionPerformed

    private void jButton1_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LoginActionPerformed

        try {
            listaUsuarios.add(new Administrador("Admin", "Elmero_mero", "123", 21));
        } catch (ExceptionNintendo e) {
            JOptionPane.showMessageDialog(this, "Edad no entra en los parametros");
        }

        try {
            listaUsuarios.add(new Vendedor(5, 2000, "Mario", "Mario", "Marioxd", "111245", 23));
        } catch (ExceptionNintendo e) {
            JOptionPane.showMessageDialog(this, "Edad no entra en los parametros");
        }

        ((Vendedor) listaUsuarios.get(1)).addJuegoVender("Mario Kart", 2012, 2, 2000);
        ((Vendedor) listaUsuarios.get(1)).addJuegoVender("Smash Bros", 2018, 4, 2400);

        try {
            listaUsuarios.add(new Vendedor(3, 3500, "Amber", "Luis Fernando", "hola_si", "asdf", 20));
        } catch (ExceptionNintendo e) {
            JOptionPane.showMessageDialog(this, "Edad no entra en los parametros");
        }

        ((Vendedor) listaUsuarios.get(2)).addJuegoVender("Mario Kart", 2012, 1, 2000);
        ((Vendedor) listaUsuarios.get(2)).addJuegoVender("Genshin Impact", 2020, 4, 3400);

        try {
            listaUsuarios.add(new Comprador(3000, "Kaeya", "Maria", "M_Chemical", "contraseñaInc", 25));
        } catch (ExceptionNintendo e) {
            JOptionPane.showMessageDialog(this, "Edad no entra en los parametros");
        }

        try {
            listaUsuarios.add(new Comprador(4500, "Isabelle", "Luisa", "Lilipop", "siiii", 20));
        } catch (ExceptionNintendo e) {
            JOptionPane.showMessageDialog(this, "Edad no entra en los parametros");
        }
        
        

        for (Usuarios U : listaUsuarios) {
            if (U.getNombreU().equals(jTextField1_Usuario.getText())
                && U.getContraseña().equals(jTextField2_Contraseña.getText())) {
                 if(U instanceof Administrador){
                    
                }
                
                if(U instanceof Vendedor){
                    
                }
                
                if(U instanceof Comprador){
                    CompradorPanel newPanelC = new CompradorPanel();
                    newPanelC.setVisible(true);
                    this.dispose(); 
                }
                
                JOptionPane.showMessageDialog(this, "Usuario encontrado");
            }

        }

    }//GEN-LAST:event_jButton1_LoginActionPerformed

    private void jButton2_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_LoginActionPerformed
        Registro newregistro = new Registro ();
        newregistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainNintendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainNintendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainNintendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainNintendo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainNintendo().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Login;
    private javax.swing.JButton jButton2_Login;
    private javax.swing.JLabel jLabel1_LogIn;
    private javax.swing.JLabel jLabel2_Login1;
    private javax.swing.JLabel jLabel3_Login;
    private javax.swing.JTextField jTextField1_Usuario;
    private javax.swing.JTextField jTextField2_Contraseña;
    // End of variables declaration//GEN-END:variables

    ArrayList<Usuarios> listaUsuarios = new ArrayList();

}
